export const CHEF_LOGIN_REQUEST = "CHEF_LOGIN_REQUEST";
export const CHEF_LOGIN_SUCCESS = "CHEF_LOGIN_SUCCESS";
export const CHEF_LOGIN_FAIL = "CHEF_LOGIN_FAIL";
export const CHEF_LOGOUT = "CHEF_LOGOUT";

export const CHEF_REGISTER_REQUEST = "CHEF_REGISTER_REQUEST";
export const CHEF_REGISTER_SUCCESS = "CHEF_REGISTER_SUCCESS";
export const CHEF_REGISTER_FAIL = "CHEF_REGISTER_FAIL";

export const CHEF_LIST_REQUEST = "CHEF_LIST_REQUEST";
export const CHEF_LIST_SUCCESS = "CHEF_LIST_SUCCESS";
export const CHEF_LIST_FAIL = "CHEF_LIST_FAIL";
